### ISSUE TITLE
Centralize validation

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell-backend#11]
There's validation happening in ValidateActor for the CLI command / API endpoint, and a separate validation path for actually running a workflow.  This should be made consistent so the "fail fast" that we have to implement for pluggable backends only needs to go in one spot.

**Comment by geoffjentry** [comment]
:+1: 

The solution I'd like to see would be that instead of spinning up on demand that the ValidateActor hangs out and listens to requests from both the REST API and WMA (and anywhere else which might care in the future).
