### ISSUE TITLE
Publish cromwell-backend artifacts to artifactory

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell-backend#7]

**Comment by geoffjentry** [comment]
@mcovarr If you don't already know how to do this I should be able to help (although I failed to write down how or double check the confluence page for accuracy). If not @kshakir can as well, although we should probably try my memory first.

Alternatively you could try just going off the confluence page but my recollection was that I felt I'd never have totally figured it out going just based on that.

**Comment by mcovarr** [comment]
You're right, I don't already know how to do this. :smile:  As much as I'd like to learn to fish this may not be the right occasion, so I'd definitely appreciate your or @kshakir's help.  Thanks!

**Comment by geoffjentry** [comment]
Let's take a stab at it on Monday and if it's a giant shrug we can call in the big guns

**Comment by francares** [comment]
Hi @geoffjentry... do you have any news on this?

**Comment by geoffjentry** [comment]
@francares Despite being closed earlier it's not quite done. There's some sort of plumbing I'm missing on the Travis side.

**Comment by geoffjentry** [comment]
@francares I believe this is working now: https://artifactory.broadinstitute.org/artifactory/webapp/search/artifact/?0&q=cromwell-backend
